name: 'Terraform Azure Deployment'

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_WORKING_DIR: './terraform'

jobs:
  init:
    name: 'Terraform Init'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

  plan:
    name: 'Terraform Plan'
    needs: init
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -var "resource_prefix=${{ github.actor }}" -out="tfplan"
        working-directory: ${{ env.TF_WORKING_DIR }}

  apply:
    name: 'Terraform Apply'
    needs: plan
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Apply
        run: terraform apply -var "resource_prefix=${{ github.actor }}" -auto-approve
        working-directory: ${{ env.TF_WORKING_DIR }}
