name: 'Combined Terraform and Cortex Scan'

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_WORKING_DIR: './terraform/azure'
  CORTEX_API_KEY: ${{secrets.CORTEX_API_KEY}}
  CORTEX_API_KEY_ID: ${{secrets.CORTEX_API_KEY_ID}}
  CORTEX_API_URL: https://api-tac-x5.xdr.sg.paloaltonetworks.com
  # Add this line to increase Terraform verbosity
  TF_LOG: INFO 

jobs:
  cortex-scan-and-deploy:
    name: 'Cortex Scan and Terraform Deploy'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      
      # --- Terraform Azure Deployment Steps ---
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Terraform Deployment
        run: |
          terraform init
          terraform plan -var "resource_prefix=${{ github.actor }}" -out="tfplan"
          terraform apply "tfplan" -auto-approve
        working-directory: ${{ env.TF_WORKING_DIR }}
