name: 'Simple Terraform Azure Deployment'

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_WORKING_DIR: './terraform'

jobs:
  deploy:
    name: 'Deploy Terraform to Azure'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Terraform Deployment
        run: |
          terraform init
          terraform plan -var "resource_prefix=${{ github.actor }}" -out="tfplan"
          terraform apply -var "resource_prefix=${{ github.actor }}" -auto-approve
        working-directory: ${{ env.TF_WORKING_DIR }}
